
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.43
 */

#ifndef SOM_Module_cmdhere_Source
#define SOM_Module_cmdhere_Source
#endif
#define cmdhroot_Class_Source
#define M_cmdhroot_Class_Source


#define MAXSTACKSIZE  262144
#define GLMAXPATH  1024

#include "cmdhere.ih"


HMODULE hResource;
INT pgmDataF[30];
CHAR CMDHEREINI[GLMAXPATH];
CHAR CMDHEREINIFN[GLMAXPATH];
CHAR CommandProcessor[GLMAXPATH];
CHAR CommandProcessorDOS[GLMAXPATH];
CHAR dosArgs[GLMAXPATH];
CHAR os2Args[GLMAXPATH];
CHAR curPathX[GLMAXPATH];
CHAR sprc[GLMAXPATH];
CHAR sprcTMP[GLMAXPATH];
ULONG progdrvNum;
CHAR progPath[GLMAXPATH];
BOOL  CHECKMOD;
ULONG TUSE;
BOOL USEDEFAULTS;
typedef struct SPData
   {
   HWND hwndF;
   HWND hwndDlg;
   CHAR dTopFold[GLMAXPATH];
   CHAR ftitle[GLMAXPATH];
   }CBD;
typedef CBD FAR *PFCBD;



BOOL setConMenu( HWND hmenu, USHORT msg);
VOID queryFoldSet(VOID);
VOID saveFoldSet(VOID);

VOID msgOK(CHAR *title, CHAR *message);
VOID debugMsgCH(CHAR ch, CHAR *varName);
VOID debugMsgStr(CHAR *str, CHAR *varName);
VOID debugMsgULong(ULONG num, CHAR *varName);
VOID debugMsgInt(INT num, CHAR *varName);
VOID getINIFQNAME(VOID);
INT chkreg(VOID);
VOID _Optlink payUp();
VOID _Optlink aboutCmdHere(PVOID n);
VOID _Optlink cmdhSettings(PVOID n);
MRESULT EXPENTRY setPageProc(HWND hwndDlg, ULONG msg,
                                               MPARAM mp1, MPARAM mp2 );
MRESULT EXPENTRY bsProc(HWND hwndDlg, ULONG msg,
                                       MPARAM mp1, MPARAM mp2);
MRESULT EXPENTRY aboutProc(HWND hwndDlg, ULONG msg,
                                            MPARAM mp1, MPARAM mp2 );






SOM_Scope BOOL  SOMLINK cmdhrootX_wpModifyPopupMenu(cmdhroot *somSelf, 
                                                    HWND hwndMenu, 
                                                    HWND hwndCnr, 
                                                    ULONG iPosition)
{
    // cmdhrootData *somThis = cmdhrootGetData(somSelf);
    cmdhrootMethodDebug("cmdhroot","cmdhrootX_wpModifyPopupMenu");

    cmdhroot_parent_WPDisk_wpModifyPopupMenu(somSelf, 
                                                                  hwndMenu, 
                                                                  hwndCnr, 
                                                                  iPosition);
    
    _wpInsertPopupMenuItems(somSelf,
                                       hwndMenu,
                                       0,
                                       hResource,
                                       IDM_CMDHERE_CMDSESSION ,
                                       WPMENUID_PRIMARY);
                                       
    setConMenu(hwndMenu, ID_OPENCOMMANDLINESESSION);
                                                  
    return(TRUE);
}



SOM_Scope BOOL  SOMLINK cmdhrootX_wpMenuItemSelected(cmdhroot *somSelf, 
                                                     HWND hwndFrame, 
                                                     ULONG ulMenuId)
{
    BOOL  result;
    
    cmdhrootData *somThis = cmdhrootGetData(somSelf);
    cmdhrootMethodDebug("cmdhroot","cmdhrootX_wpMenuItemSelected");
    
    result = TRUE;

    switch( ulMenuId )
       {
       case ID_CMDHEREABOUT: 
          {
          _beginthread(aboutCmdHere, NULL, MAXSTACKSIZE, NULL);
          }
          break;
          
       case ID_CMDHERESETTINGS: 
          {
          _beginthread(cmdhSettings, NULL, MAXSTACKSIZE, (PVOID)0);
          }
          break;
          
       case ID_OPENCOMMANDLINESESSION: 
       case ID_CLSOS2W: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          ULONG drv;
          WPRootFolder *rf;
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          drv = _wpQueryLogicalDrive(somSelf); 
          rf = _wpQueryRootFolder(somSelf);
          _wpQueryRealName(rf, dTopFold, &rsize, TRUE);
          if( dTopFold[strlen(dTopFold)-1] != '\\' )
             strcat(dTopFold, "\\");
             
             			          
          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();  

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessor, "cmd.exe");   
             }
          else
             strcpy(pgmarg, os2Args);
          
          pDetails = malloc(sizeof(PROGDETAILS)) ;
          
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "OS/2 Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_WINDOWABLEVIO;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessor;
             pDetails->pszParameters   = pgmarg;
             // pDetails->pszExecutable   = "DETACH.EXE";
             // pDetails->pszParameters   = "cmd.exe";
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
 
             free(pDetails);   
             }  
          }
          break;
           
       case ID_CLSOS2FS: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          ULONG drv;
          WPRootFolder *rf;
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          drv = _wpQueryLogicalDrive(somSelf); 
          rf = _wpQueryRootFolder(somSelf);
          _wpQueryRealName(rf, dTopFold, &rsize, TRUE);
          if( dTopFold[strlen(dTopFold)-1] != '\\' )
             strcat(dTopFold, "\\");


          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessor, "cmd.exe");   
             }
          else
             strcpy(pgmarg, os2Args);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "OS/2 Full Screen Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_FULLSCREEN;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessor;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
 
             free(pDetails);   
             }  
          }
          break;
    

    
       //*************************** DOS BEGIN ****************  
       //*************************** DOS BEGIN ****************  

    
       case ID_CLDOSW: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          ULONG drv;
          WPRootFolder *rf;
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          drv = _wpQueryLogicalDrive(somSelf); 
          rf = _wpQueryRootFolder(somSelf);
          _wpQueryRealName(rf, dTopFold, &rsize, TRUE);
          if( dTopFold[strlen(dTopFold)-1] != '\\' )
             strcat(dTopFold, "\\");


          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();
   
          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessorDOS, "command.com");   
             }
          else
             strcpy(pgmarg, dosArgs);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "DOS Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_WINDOWEDVDM;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessorDOS;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
 
             free(pDetails);   
             }
          }
          break;
          
       case ID_CLDOSFS: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          ULONG drv;
          WPRootFolder *rf;
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          drv = _wpQueryLogicalDrive(somSelf); 
          rf = _wpQueryRootFolder(somSelf);
          _wpQueryRealName(rf, dTopFold, &rsize, TRUE);
          if( dTopFold[strlen(dTopFold)-1] != '\\' )
             strcat(dTopFold, "\\");


          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )	   
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);
             }
          queryFoldSet();

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessorDOS, "command.com");   
             }
          else
             strcpy(pgmarg, dosArgs);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "DOS Full Screen Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_VDM;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessorDOS;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
             free(pDetails);   
             }    
          }
          break;  
       
          
       //*************************** DOS END ****************  
       //*************************** DOS END ****************  
       
       
       default:
          result = cmdhroot_parent_WPDisk_wpMenuItemSelected(somSelf,
                                                                                    hwndFrame,
                                                                                    ulMenuId);
          break;
       }


    return(result);
}


SOM_Scope void  SOMLINK cmdhrootX_wpclsInitData(M_cmdhroot *somSelf)
{
    CHAR     szBuffer[BUFFERSIZE];
    
    /* M_cmdhrootData *somThis = M_cmdhrootGetData(somSelf); */
    M_cmdhrootMethodDebug("M_cmdhroot","cmdhrootX_wpclsInitData");

    CHECKMOD = TRUE;   
    /* DosLoadModule(szBuffer,
                         BUFFERSIZE,
                         RESOURCE_MODULE,
                         &hResource); */
                               
    M_cmdhroot_parent_M_WPDisk_wpclsInitData(somSelf);
}


SOM_Scope void  SOMLINK cmdhrootX_wpclsUnInitData(M_cmdhroot *somSelf)
{
    /* M_cmdhrootData *somThis = M_cmdhrootGetData(somSelf); */
    M_cmdhrootMethodDebug("M_cmdhroot","cmdhrootX_wpclsUnInitData");

    // if( hResource != NULLHANDLE )
    //    DosFreeModule( hResource );

    M_cmdhroot_parent_M_WPDisk_wpclsUnInitData(somSelf);
}


SOM_Scope BOOL  SOMLINK cmdhrootX_wpclsCreateDefaultTemplates(M_cmdhroot *somSelf, 
                                                              WPObject* Folder)
{
    /* M_cmdhrootData *somThis = M_cmdhrootGetData(somSelf); */
    M_cmdhrootMethodDebug("M_cmdhroot","cmdhrootX_wpclsCreateDefaultTemplates");

    // M_cmdhroot_parent_M_WPDisk_wpclsCreateDefaultTemplates(somSelf, Folder);
    
    return(TRUE);
    
//    return (M_cmdhroot_parent_M_WPDisk_wpclsCreateDefaultTemplates(somSelf, Folder));
}







//************************************************************************
//***************** CMDHEREFOLDER OBJECT *********************************
//************************************************************************


SOM_Scope BOOL  SOMLINK cmdherefolderX_wpModifyPopupMenu(cmdherefolder *somSelf, 
                                                   HWND hwndMenu, 
                                                   HWND hwndCnr, 
                                                   ULONG iPosition)
{
    cmdherefolderData *somThis = cmdherefolderGetData(somSelf);
    cmdherefolderMethodDebug("cmdherefolder","cmdherefolderX_wpModifyPopupMenu");

    cmdherefolder_parent_WPFolder_wpModifyPopupMenu(somSelf, 
                                                                            hwndMenu, 
                                                                            hwndCnr, 
                                                                            iPosition);

    _wpInsertPopupMenuItems(somSelf,
                                       hwndMenu,
                                       0,
                                       hResource,
                                       IDM_CMDHERE_CMDSESSION ,
                                       WPMENUID_PRIMARY);
                                                  
    setConMenu(hwndMenu, ID_OPENCOMMANDLINESESSION);
    
    return(TRUE);                                   
}






SOM_Scope BOOL  SOMLINK cmdherefolderX_wpMenuItemSelected(cmdherefolder *somSelf, 
                                                    HWND hwndFrame, 
                                                    ULONG ulMenuId)
{
    BOOL  result;

    cmdherefolderData *somThis = cmdherefolderGetData(somSelf);
    cmdherefolderMethodDebug("cmdherefolder","cmdherefolderX_wpMenuItemSelected");
    
    result = TRUE;

    switch( ulMenuId )
       {
       case ID_CMDHEREABOUT: 
          {
          _beginthread(aboutCmdHere, NULL, MAXSTACKSIZE, NULL);
          }
          break;
          
       case ID_CMDHERESETTINGS: 
          {
          _beginthread(cmdhSettings, NULL, MAXSTACKSIZE, (PVOID)0);
          }
          break;
          
       case ID_OPENCOMMANDLINESESSION: 
       case ID_CLSOS2W: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          
          
          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          _wpQueryRealName(somSelf, dTopFold, &rsize, TRUE);

          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )	   
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();
          
          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessor, "cmd.exe");   
             }
          else
             strcpy(pgmarg, os2Args);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "OS/2 Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_WINDOWABLEVIO;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessor;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
 
             free(pDetails);
             _beginthread(payUp, NULL, MAXSTACKSIZE, NULL);
             }  
          }
          break;

       case ID_CLSOS2FS: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          _wpQueryRealName(somSelf, dTopFold, &rsize, TRUE);

          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )	   
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessor, "cmd.exe");   
             }
          else
             strcpy(pgmarg, os2Args);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "OS/2 Full Screen Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_FULLSCREEN;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessor;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
 
             free(pDetails);   
             _beginthread(payUp, NULL, MAXSTACKSIZE, NULL);
             }  
          }
          break;

    
       //*************************** DOS START ****************  
       //*************************** DOS START ****************  


       case ID_CLDOSW: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          _wpQueryRealName(somSelf, dTopFold, &rsize, TRUE);

          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )	   
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);
             }
          queryFoldSet();

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessorDOS, "command.com");   
             }
          else
             strcpy(pgmarg, dosArgs);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "DOS Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_WINDOWEDVDM;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessorDOS;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;
                          
             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
              
             free(pDetails);   
             _beginthread(payUp, NULL, MAXSTACKSIZE, NULL);
             }   
          }
          break;

          
       case ID_CLDOSFS: 
          {
          PPROGDETAILS  pDetails;
          ULONG flgs;
          CHAR pgmarg[60];
          CHAR dTopFold[GLMAXPATH];
          CHAR tbTitle[GLMAXPATH+100];
          ULONG rsize = sizeof(dTopFold);
          

          USEDEFAULTS = FALSE;
          if( (WinGetKeyState(HWND_DESKTOP, VK_F11)&0x8000) )
             USEDEFAULTS = TRUE;
          _wpQueryRealName(somSelf, dTopFold, &rsize, TRUE);

          if( CHECKMOD )
             {
	  queryFoldSet();
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "InstallationPath",
		                    "", CMDHEREINI, GLMAXPATH);
             PrfQueryProfileString(HINI_USERPROFILE, 
                                         "CmdHereIsInstalled", 
                                         "rc",
		                    "", sprcTMP, GLMAXPATH);
	   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
             if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
                strcat(CMDHEREINIFN, "\\");
             strcat(CMDHEREINIFN, "CMDHERE.INI");   
	   if( strlen(sprcTMP) > 0 )	   
	      {
	      strcpy(sprc, sprcTMP);	                    
                 PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
                 saveFoldSet();
                 }
             CHECKMOD = FALSE;
             }			          
          if( strlen(CMDHEREINI) == 0 )
             {
             getINIFQNAME();
             PrfWriteProfileString(HINI_USERPROFILE, 
                                        "CmdHereIsInstalled",
                                        "InstallationPath", 
                                        CMDHEREINI);

             }
          queryFoldSet();

          if( USEDEFAULTS )
             {
             strcpy(pgmarg, "");   
             strcpy(CommandProcessorDOS, "command.com");   
             }
          else
             strcpy(pgmarg, dosArgs);

          pDetails = malloc(sizeof(PROGDETAILS)) ;
      
          if( pDetails )
             {
             flgs = SWP_ACTIVATE | SWP_SHOW;
             strcpy(tbTitle, "DOS Full Screen Session : ");
             strcat(tbTitle, dTopFold);

             pDetails->Length          = sizeof(PROGDETAILS);
             pDetails->progt.progc     = PROG_VDM;
             pDetails->progt.fbVisible = SHE_VISIBLE;
             pDetails->pszTitle        = tbTitle;
             pDetails->pszExecutable   = CommandProcessorDOS;
             pDetails->pszParameters   = pgmarg;
             pDetails->pszStartupDir   = dTopFold;
             pDetails->pszIcon         = NULL;
             pDetails->pszEnvironment  = NULL;
             pDetails->swpInitial.fl   = flgs;
             pDetails->swpInitial.cy   = 0;
             pDetails->swpInitial.cx   = 0;
             pDetails->swpInitial.y    = 0;
             pDetails->swpInitial.x    = 0;
             pDetails->swpInitial.hwndInsertBehind = HWND_TOP;
             pDetails->swpInitial.hwnd             = NULLHANDLE;
             pDetails->swpInitial.ulReserved1      = 0;
             pDetails->swpInitial.ulReserved2      = 0;

             WinStartApp( NULLHANDLE, pDetails, NULL, NULL, SAF_INSTALLEDCMDLINE);  
             free(pDetails);   
             _beginthread(payUp, NULL, MAXSTACKSIZE, NULL);
             }
          }
          break;


       //*************************** DOS END ****************  
       //*************************** DOS END ****************  
       
       
          
       default:
          result = cmdherefolder_parent_WPFolder_wpMenuItemSelected(somSelf,
                                                           hwndFrame,
                                                           ulMenuId);
          break;
       }

    return(result);
}





/*
 * pszMyTitle:   noget, noset;
 */

SOM_Scope BOOL  SOMLINK cmdherefolderX_wpclsCreateDefaultTemplates(M_cmdherefolder *somSelf, 
                                                                   WPObject* Folder)
{
    // M_cmdherefolderData *somThis = M_cmdherefolderGetData(somSelf);
    M_cmdherefolderMethodDebug("M_cmdherefolder","cmdherefolderX_wpclsCreateDefaultTemplates");

    // M_cmdherefolder_parent_M_WPFolder_wpclsCreateDefaultTemplates(somSelf, 
    //                                                                      Folder);
                                                                          
    return(TRUE);
                                                                          
//    return (M_cmdherefolder_parent_M_WPFolder_wpclsCreateDefaultTemplates(somSelf, 
//                                                                          Folder));
}


SOM_Scope void  SOMLINK cmdherefolderX_wpclsInitData(M_cmdherefolder *somSelf)
{
    CHAR     szBuffer[BUFFERSIZE];
    APIRET rc;
    
    M_cmdherefolderData *somThis = M_cmdherefolderGetData(somSelf);
    M_cmdherefolderMethodDebug("M_cmdherefolder","cmdherefolderX_wpclsInitData");

    CHECKMOD = TRUE;   
    TUSE = 0;
    rc = DosLoadModule(szBuffer,
                               BUFFERSIZE,
                               RESOURCE_MODULE,
                               &hResource);
    
    M_cmdherefolder_parent_M_WPFolder_wpclsInitData(somSelf);
}



SOM_Scope void  SOMLINK cmdherefolderX_wpclsUnInitData(M_cmdherefolder *somSelf)
{
    M_cmdherefolderData *somThis = M_cmdherefolderGetData(somSelf);
    M_cmdherefolderMethodDebug("M_cmdherefolder","cmdherefolderX_wpclsUnInitData");

    saveFoldSet();
    PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled",
			"InstallationPath", CMDHEREINI);
    
    // if( hResource != NULLHANDLE )
    //   DosFreeModule( hResource );

    M_cmdherefolder_parent_M_WPFolder_wpclsUnInitData(somSelf);
}


/******************** Support Functions **************************/
/******************** Support Functions **************************/
/******************** Support Functions **************************/









VOID _Optlink cmdhSettings(PVOID n)
{
HAB habT;
HMQ hmqT;
HWND hwndF;
CBD spSet;
// SOMAny *sSelf;


habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

// sSelf = (SOMAny *)n;          
if( CHECKMOD )
   {
   queryFoldSet();
   PrfQueryProfileString(HINI_USERPROFILE, 
                                 "CmdHereIsInstalled", 
                                 "InstallationPath",
                                 "", CMDHEREINI, GLMAXPATH);
   PrfQueryProfileString(HINI_USERPROFILE, 
                                  "CmdHereIsInstalled", 
                                  "rc",
	                       "", sprcTMP, GLMAXPATH);
   strcpy(CMDHEREINIFN, CMDHEREINI);	                    
   if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
      strcat(CMDHEREINIFN, "\\");
   strcat(CMDHEREINIFN, "CMDHERE.INI");   
   if( strlen(sprcTMP) > 0 )
      {
      strcpy(sprc, sprcTMP);	                    
      PrfWriteProfileString(HINI_USERPROFILE, "CmdHereIsInstalled", "rc", "");
      saveFoldSet();
      }
   CHECKMOD = FALSE;
   }			          

if( strlen(CMDHEREINI) == 0 )
   {
   getINIFQNAME();
   PrfWriteProfileString(HINI_USERPROFILE, 
                                "CmdHereIsInstalled",
                                "InstallationPath", 
                                CMDHEREINI);

   }

queryFoldSet();
hwndF = WinLoadDlg(HWND_DESKTOP,
                              HWND_DESKTOP,
                              setPageProc,
                              hResource,
                              ID_SETPAGE, &spSet);
WinProcessDlg(hwndF);



WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}




VOID _Optlink aboutCmdHere(PVOID n)
{
HAB habT;
HMQ hmqT;
HWND hwndF;

habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);


hwndF = WinLoadDlg(HWND_DESKTOP,
                              HWND_DESKTOP,
                              aboutProc,
                              hResource,
                              ID_ABOUTCMDHERE, 0);
WinProcessDlg(hwndF);


WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}





VOID getINIFQNAME(VOID)
{
APIRET rc;
CHAR fqprogPath[GLMAXPATH];

rc = DosQueryModuleName(hResource,  sizeof(fqprogPath), fqprogPath);                     
if( rc == 0 )                     
   {
   INT num, mark;
 
   strcpy(progPath, fqprogPath);
   mark = -1;
   for( num=0;num<strlen(fqprogPath);num++ )
      {
      if( fqprogPath[num] == '\\' )
         mark = num;
      }
   if( mark )
      progPath[mark] = '\0';
   }
strcpy(CMDHEREINIFN, progPath);
if( strlen(CMDHEREINIFN) > 1 )
   {
   if( CMDHEREINIFN[strlen(CMDHEREINIFN) - 1] != '\\' )
      strcat(CMDHEREINIFN, "\\");
   strcat(CMDHEREINIFN, "CMDHERE.INI");   
   }   
}



BOOL setConMenu( HWND hmenu, USHORT msg)
{
MENUITEM mi ;
ULONG ulStyle ;

WinSendMsg( hmenu, MM_QUERYITEM, MPFROM2SHORT( msg, TRUE), MPFROMP( &mi)) ;

if( !mi.hwndSubMenu)
   return FALSE ;

ulStyle = WinQueryWindowULong( mi.hwndSubMenu, QWL_STYLE) ;
if( WinSetWindowULong( mi.hwndSubMenu, QWL_STYLE, ulStyle | MS_CONDITIONALCASCADE))
   return TRUE ;

return FALSE ;
}




VOID queryFoldSet(VOID)
{
ULONG rSizeX;
HINI MYHINI;

if ( (MYHINI = PrfOpenProfile(0, CMDHEREINIFN )) != NULLHANDLE )
   {
   PrfQueryProfileSize(MYHINI,
                             "CMDHEREOS2",
                             "CMDHEREOS2SET", &rSizeX);
   if ( rSizeX == (sizeof(pgmDataF)) )
      {
      PrfQueryProfileData(MYHINI,
                                 "CMDHEREOS2",
                                 "CMDHEREOS2SET",
                                 &pgmDataF, &rSizeX);
      }
   else
      {
      pgmDataF[0] = 0;
      pgmDataF[1] = 0;
      pgmDataF[2] = 0;
      pgmDataF[3] = 0;
      pgmDataF[4] = 0;
      pgmDataF[5] = 0;
      pgmDataF[6] = 0;
      pgmDataF[7] = 0;
      pgmDataF[8] = 0;
      pgmDataF[9] = 0;
      pgmDataF[10] = 0;
      pgmDataF[11] = 0;
      pgmDataF[12] = 0;
      pgmDataF[13] = 0;
      pgmDataF[14] = 0;
      pgmDataF[15] = 0;
      pgmDataF[16] = 0;
      pgmDataF[17] = 0;
      pgmDataF[18] = 0;
      pgmDataF[19] = 0;
      pgmDataF[20] = 0;
      }

   PrfQueryProfileString(MYHINI, "CMDHEREOS2", "CMDHERECMDPROC",
                      "CMD.EXE", CommandProcessor, CCHMAXPATH );
   PrfQueryProfileString(MYHINI, "CMDHEREOS2", "CMDHERECMDPROCDOS",
                      "COMMAND.COM", CommandProcessorDOS, CCHMAXPATH );
   PrfQueryProfileString(MYHINI, "CMDHEREOS2", "CMDHERECMDARGS",
                      "", os2Args, CCHMAXPATH );
   PrfQueryProfileString(MYHINI, "CMDHEREOS2", "CMDHERECMDARGSDOS",
                      "", dosArgs, CCHMAXPATH );
   PrfQueryProfileString(MYHINI, "CMDHEREOS2", "CMDHERESPRC",
                      "", sprc, CCHMAXPATH );
   } 
else
   {
   strcpy(CommandProcessor, "CMD.EXE");
   strcpy(CommandProcessorDOS, "COMMAND.COM");
   strcpy(sprc, "");
   strcpy(os2Args, "");
   strcpy(dosArgs, "");
   pgmDataF[0] = 0;
   pgmDataF[1] = 0;
   pgmDataF[2] = 0;
   pgmDataF[3] = 0;
   pgmDataF[4] = 0;
   pgmDataF[5] = 0;
   pgmDataF[6] = 0;
   pgmDataF[7] = 0;
   pgmDataF[8] = 0;
   pgmDataF[9] = 0;
   pgmDataF[10] = 0;
   pgmDataF[11] = 0;
   pgmDataF[12] = 0;
   pgmDataF[13] = 0;
   pgmDataF[14] = 0;
   pgmDataF[15] = 0;
   pgmDataF[16] = 0;
   pgmDataF[17] = 0;
   pgmDataF[18] = 0;
   pgmDataF[19] = 0;
   pgmDataF[20] = 0;
   }                        
}



VOID saveFoldSet(VOID)
{
HINI MYHINI;

if ( (MYHINI = PrfOpenProfile(0, CMDHEREINIFN )) != NULLHANDLE )
   {
   PrfWriteProfileData(MYHINI,
                             "CMDHEREOS2",
                             "CMDHEREOS2SET",
                             &pgmDataF,
                             sizeof(pgmDataF));
   PrfWriteProfileString(MYHINI, "CMDHEREOS2",
                              "CMDHERECMDPROC", CommandProcessor);
   PrfWriteProfileString(MYHINI, "CMDHEREOS2",
                              "CMDHERECMDPROCDOS", CommandProcessorDOS);
   PrfWriteProfileString(MYHINI, "CMDHEREOS2",
                              "CMDHERECMDARGS", os2Args);
   PrfWriteProfileString(MYHINI, "CMDHEREOS2",
                              "CMDHERECMDARGSDOS", dosArgs);
   PrfWriteProfileString(MYHINI, "CMDHEREOS2",
                              "CMDHERESPRC", sprc);
   }                   
}


VOID msgOK(CHAR *title, CHAR *message)
{
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     message,
                     title,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}


VOID debugMsgStr(CHAR *str, CHAR *varName)
{
CHAR dMsg[255] = "Debug Message string ... ";

strcat(dMsg, varName),
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     str,
                     dMsg,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}

VOID debugMsgInt(INT num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message Int ... ";

strcat(dMsg, varName),
itoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     str,
                     dMsg,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}

VOID debugMsgULong(ULONG num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message ULong ... ";

strcat(dMsg, varName),
ultoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     str,
                     dMsg,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}


VOID debugMsgLong(LONG num, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message Long ... ";

strcat(dMsg, varName),
ltoa(num, str, 10);
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     str,
                     dMsg,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}


VOID debugMsgCH(CHAR ch, CHAR *varName)
{
CHAR str[255] = "";
CHAR dMsg[255] = "Debug Message char ... ";

strcat(dMsg, varName),
str[0] = ch;
str[1] = '\0';
WinMessageBox(HWND_DESKTOP,
                     HWND_DESKTOP,
                     str,
                     dMsg,
                     0,
                     MB_OK | MB_ICONEXCLAMATION );
}



MRESULT EXPENTRY setPageProc(HWND hwndDlg, ULONG msg,
                                            MPARAM mp1, MPARAM mp2 )
{
static CBD prdlocal, *pprdcurrent;
switch ( msg )
   {
   case WM_INITDLG:
      {
      POINTL mptl;
      LONG offx, offy, xx, yy, xfact, yfact, dtHeight, dtWidth;
      SWP swp;

      pprdcurrent = PVOIDFROMMP (mp2) ;
      prdlocal = *pprdcurrent ;
      offx = 0;
      offy = 0;
      xfact = 215;  // 118
      yfact = 25;

      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-xfact)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-xfact)+5) - dtWidth;
         }
      if( (mptl.x-(xfact+5)) < 0 )
         {
         offx = (mptl.x-(xfact+5)) ;
         }
      if( (mptl.y+(swp.cy-yfact)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(yfact+5)) < 0 )
         {
         offy = (mptl.y-(yfact+5));
         }

      xx = (mptl.x - 265) - offx;  // 220
      yy = (mptl.y - 24) - offy;   // 58

      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );

      WinSendDlgItemMsg(hwndDlg, 
                                ID_SPOS2CMDPROC,
                                EM_SETTEXTLIMIT,
			 MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSendDlgItemMsg(hwndDlg, 
                                ID_SPOS2CMDARGS,
                                EM_SETTEXTLIMIT,
			 MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSendDlgItemMsg(hwndDlg, 
                                ID_SPDOSCMDPROC,
                                EM_SETTEXTLIMIT,
			 MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSendDlgItemMsg(hwndDlg, 
                                ID_SPDOSCMDARGS,
                                EM_SETTEXTLIMIT,
			 MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSendDlgItemMsg(hwndDlg, 
                                  ID_SPRC,
                                  EM_SETTEXTLIMIT,
			  MPFROM2SHORT(GLMAXPATH,0),NULL);
      WinSetDlgItemText (hwndDlg, ID_SPOS2CMDPROC, CommandProcessor);
      WinSetDlgItemText (hwndDlg, ID_SPOS2CMDARGS, os2Args);
      WinSetDlgItemText (hwndDlg, ID_SPDOSCMDPROC, CommandProcessorDOS);
      WinSetDlgItemText (hwndDlg, ID_SPDOSCMDARGS, dosArgs);
      WinSetDlgItemText (hwndDlg, ID_SPRC, sprc);
      }
      break;

   case WM_CLOSE:
      WinDismissDlg(hwndDlg, FALSE);
      return(MRESULT)FALSE;
      break;

   case WM_DESTROY:
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
         {
         case ID_SPSAVE :
            {
            WinQueryDlgItemText(hwndDlg,
                                         ID_SPOS2CMDPROC,
                                         sizeof(CommandProcessor),
                                         CommandProcessor);
            WinQueryDlgItemText(hwndDlg,
                                         ID_SPOS2CMDARGS,
                                         sizeof(os2Args),
                                         os2Args);
            WinQueryDlgItemText(hwndDlg,
                                         ID_SPDOSCMDPROC,
                                         sizeof(CommandProcessorDOS),
                                         CommandProcessorDOS);
            WinQueryDlgItemText(hwndDlg,
                                         ID_SPDOSCMDARGS,
                                         sizeof(dosArgs),
                                         dosArgs);
            WinQueryDlgItemText(hwndDlg,
                                           ID_SPRC,
                                           sizeof(sprc),
                                           sprc);
            saveFoldSet();                             
            WinDismissDlg(hwndDlg, TRUE);
            *pprdcurrent = prdlocal ;
            return(MRESULT)TRUE;
            }
            break;  

         default :
            return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
         }
   }
return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
}



INT chkreg(VOID)
{
if(strlen(sprc) == 13)
   {
   if( stricmp(sprc, ",,.........,,") == 0 || stricmp(sprc, "...CmdHere...") == 0 || stricmp(sprc, "...=======...") == 0 )
      return(1);
   else
      return(0);   
   }
else
   return(0);   
}



VOID _Optlink payUp()
{
HAB habT;
HMQ hmqT;
HWND hwndDlg, hwndL;

habT = WinInitialize(0);
hmqT = WinCreateMsgQueue(habT, 0);
WinCancelShutdown(hmqT, TRUE);

TUSE++;
if( !chkreg() && TUSE > 2 )
   {
   hwndL = WinLoadDlg(HWND_DESKTOP,
                                 HWND_DESKTOP,
	                      bsProc,
	                      hResource,
	                      ID_BUGSCREEN,
	                      NULL);

   WinProcessDlg(hwndL);
   TUSE = 0;
   }

WinDestroyMsgQueue(hmqT);
WinTerminate(habT);
_endthread();
}



MRESULT EXPENTRY bsProc( HWND hwndDlg, ULONG msg,
                          MPARAM mp1, MPARAM mp2 )
{
switch ( msg )
   {
   case WM_INITDLG:
      {
      POINTL mptl;
      LONG offx, offy, xx, yy, xfact, yfact, dtHeight, dtWidth;
      SWP swp;

      offx = 0;
      offy = 0;
      xfact = 215;  // 118
      yfact = 25;

      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-xfact)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-xfact)+5) - dtWidth;
         }
      if( (mptl.x-(xfact+5)) < 0 )
         {
         offx = (mptl.x-(xfact+5)) ;
         }
      if( (mptl.y+(swp.cy-yfact)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(yfact+5)) < 0 )
         {
         offy = (mptl.y-(yfact+5));
         }

      xx = (mptl.x - 220) - offx;  // 220
      yy = (mptl.y - 28) - offy;   // 58

      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );
      }
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
         {
         case ID_BSOK:
            {
            INT i;
            
            for(i=0;i<2;i++)
               {
               DosSleep(200);
               DosBeep(300, 200);
               }
            WinDismissDlg (hwndDlg, TRUE);
            }
            break;
         }

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}


MRESULT EXPENTRY aboutProc( HWND hwndDlg, ULONG msg,
                          MPARAM mp1, MPARAM mp2 )
{
switch ( msg )
   {
   case WM_INITDLG:
      {
      POINTL mptl;
      LONG offx, offy, xx, yy, xfact, yfact, dtHeight, dtWidth;
      SWP swp;

      offx = 0;
      offy = 0;
      xfact = 215;  // 118
      yfact = 25;

      dtHeight = WinQuerySysValue(HWND_DESKTOP,SV_CYSCREEN);
      dtWidth = WinQuerySysValue(HWND_DESKTOP,SV_CXSCREEN);
      WinQueryWindowPos(hwndDlg, (PSWP) &swp);
      WinQueryPointerPos(HWND_DESKTOP, &mptl);

      if( (mptl.x+(swp.cx-xfact)+5) > dtWidth )
         {
         offx =  (mptl.x+(swp.cx-xfact)+5) - dtWidth;
         }
      if( (mptl.x-(xfact+5)) < 0 )
         {
         offx = (mptl.x-(xfact+5)) ;
         }
      if( (mptl.y+(swp.cy-yfact)+5) > dtHeight )
         {
         offy = (mptl.y+(swp.cy-5)+10) - dtHeight;
         }
      if( (mptl.y-(yfact+5)) < 0 )
         {
         offy = (mptl.y-(yfact+5));
         }

      xx = (mptl.x - 220) - offx;  // 220
      yy = (mptl.y - 28) - offy;   // 58

      WinSetWindowPos(hwndDlg, HWND_TOP, xx, yy, 0, 0,
                      SWP_ACTIVATE | SWP_MOVE | SWP_SHOW );
      }                
      break;

   case WM_COMMAND :
      switch( SHORT1FROMMP( mp1 ) )
         {
         case ID_ABOUTOK:
            {
            WinDismissDlg (hwndDlg, TRUE);
            }
            break;
         }

   default :
      return WinDefDlgProc( hwndDlg, msg, mp1, mp2 );
   }
return (MRESULT) FALSE;
}



