
/*
 * This file was generated by the SOM Compiler.
 * FileName: F:\cmdhere\WPSDLL\cmdhere.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 *    CMDHERE.IDL - A WorkFrame/2* Quickstart WPS/SOM application
 * 
 *    Copyright (C) 1995 IBM Corporation
 * 
 *        DISCLAIMER OF WARRANTIES.  The following [enclosed] code is
 *        sample code created by IBM Corporation. This sample code is not
 *        part of any standard or IBM product and is provided to you solely
 *        for  the purpose of assisting you in the development of your
 *        applications.  The code is provided "AS IS", without
 *        warranty of any kind.  IBM shall not be liable for any damages
 *        arising out of your use of the sample code, even if they have been
 *        advised of the possibility of such damages.
 * 
 *  =====================================================================#
 *                                                                       #
 *   CLASS: cmdherefolder                                                    #
 *                                                                       #
 *   CLASS HIERARCHY:                                                    #
 *                                                                       #
 *       SOMObject                                                       #
 *         ÀÄÄ WPObject                                                  #
 *               ÀÄÄ WPFileSystem                                        #
 *                     ÀÄÄ cmdhere                                      #
 *                                                                       #
 *   DESCRIPTION:                                                        #
 *                                                                       #
 *   This is a generic WPS object class.  The object displays the name   #
 *   of any object dropped on it. If you select the "Select me" item     #
 *   from its pop-up menu, you will get online help on the object.       #
 *   You may use this application as a template for your own WPS objects.#
 *   Many of the usual methods are overridden.                           #
 *                                                                       #
 *   Instances of this class are Workplace Shell objects.                #
 *                                                                       #
 *  =====================================================================#
 */


#ifndef SOM_cmdhroot_h
#define SOM_cmdhroot_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef cmdhroot
#define cmdhroot SOMObject
#endif
#include <wpdisk.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef WPRootFolder
    #define WPRootFolder SOMObject
#endif /* WPRootFolder */
#ifndef M_WPDisk
    #define M_WPDisk SOMObject
#endif /* M_WPDisk */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_cmdhroot
    #define M_cmdhroot SOMObject
#endif /* M_cmdhroot */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_WPRootFolder
    #define M_WPRootFolder SOMObject
#endif /* M_WPRootFolder */
#ifndef M_cmdherefolder
    #define M_cmdherefolder SOMObject
#endif /* M_cmdherefolder */

/*
 * End of user-defined types.
 */

#define cmdhroot_MajorVersion 1
#define cmdhroot_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define cmdhrootNewClass cmdhrootc
#pragma linkage(cmdhrootc, system)
#define cmdhrootClassData cmdhrootd
#define cmdhrootCClassData cmdhrootx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cmdhere.h>
/*--------------Migration------------*/
#define cmdhroot_classObj cmdhrootClassData.classObject
#define _cmdhroot cmdhroot_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK cmdhrootNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(cmdhrootNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct cmdhrootClassDataStructure {
	SOMClass *classObject;
} SOMDLINK cmdhrootClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct cmdhrootCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK cmdhrootCClassData;

/*
 * New and Renew macros for cmdhroot
 */
#define cmdhrootNew() \
   (_somNew(_cmdhroot ? _cmdhroot : cmdhrootNewClass(cmdhroot_MajorVersion, cmdhroot_MinorVersion)))
#define cmdhrootRenew(buf) \
   (_somRenew(_cmdhroot ? _cmdhroot : cmdhrootNewClass(cmdhroot_MajorVersion, cmdhroot_MinorVersion), buf))

/*
 * Override method: wpModifyPopupMenu
 */
#define cmdhroot_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define cmdhroot_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define cmdhroot_wpAddDiskDetailsPage WPDisk_wpAddDiskDetailsPage
#define cmdhroot_wpQueryDriveLockStatus WPDisk_wpQueryDriveLockStatus
#define cmdhroot_wpEjectDisk WPDisk_wpEjectDisk
#define cmdhroot_wpLockDrive WPDisk_wpLockDrive
#define cmdhroot_wpQueryLogicalDrive WPDisk_wpQueryLogicalDrive
#define cmdhroot_wpQueryRootFolder WPDisk_wpQueryRootFolder
#define cmdhroot_wpSetCorrectDiskIcon WPDisk_wpSetCorrectDiskIcon
#define cmdhroot_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define cmdhroot_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define cmdhroot_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define cmdhroot_wpAddSettingsPages WPObject_wpAddSettingsPages
#define cmdhroot_wpAddToObjUseList WPObject_wpAddToObjUseList
#define cmdhroot_wpAllocMem WPObject_wpAllocMem
#define cmdhroot_wpAppendObject WPObject_wpAppendObject
#define cmdhroot_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define cmdhroot_wpClose WPObject_wpClose
#define cmdhroot_wpCnrInsertObject WPObject_wpCnrInsertObject
#define cmdhroot_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define cmdhroot_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define cmdhroot_wpConfirmDelete WPObject_wpConfirmDelete
#define cmdhroot_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define cmdhroot_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define cmdhroot_wpCopyObject WPObject_wpCopyObject
#define cmdhroot_wpCreateAnother WPObject_wpCreateAnother
#define cmdhroot_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define cmdhroot_wpCreateShadowObject WPObject_wpCreateShadowObject
#define cmdhroot_wpDelete WPObject_wpDelete
#define cmdhroot_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define cmdhroot_wpDisplayHelp WPObject_wpDisplayHelp
#define cmdhroot_wpDisplayMenu WPObject_wpDisplayMenu
#define cmdhroot_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define cmdhroot_wpDraggedOverObject WPObject_wpDraggedOverObject
#define cmdhroot_wpDragOver WPObject_wpDragOver
#define cmdhroot_wpDrop WPObject_wpDrop
#define cmdhroot_wpDroppedOnObject WPObject_wpDroppedOnObject
#define cmdhroot_wpEndConversation WPObject_wpEndConversation
#define cmdhroot_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define cmdhroot_wpFindUseItem WPObject_wpFindUseItem
#define cmdhroot_wpFormatDragItem WPObject_wpFormatDragItem
#define cmdhroot_wpFree WPObject_wpFree
#define cmdhroot_wpFreeMem WPObject_wpFreeMem
#define cmdhroot_wpHide WPObject_wpHide
#define cmdhroot_wpInitData WPObject_wpInitData
#define cmdhroot_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define cmdhroot_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define cmdhroot_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define cmdhroot_wpMoveObject WPObject_wpMoveObject
#define cmdhroot_wpOpen WPObject_wpOpen
#define cmdhroot_wpPrintObject WPObject_wpPrintObject
#define cmdhroot_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define cmdhroot_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define cmdhroot_wpQueryConfirmations WPObject_wpQueryConfirmations
#define cmdhroot_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define cmdhroot_wpQueryDefaultView WPObject_wpQueryDefaultView
#define cmdhroot_wpQueryDetailsData WPObject_wpQueryDetailsData
#define cmdhroot_wpQueryError WPObject_wpQueryError
#define cmdhroot_wpSetFolder WPObject_wpSetFolder
#define cmdhroot_wpQueryFolder WPObject_wpQueryFolder
#define cmdhroot_wpQueryIcon WPObject_wpQueryIcon
#define cmdhroot_wpQueryIconData WPObject_wpQueryIconData
#define cmdhroot_wpQueryMinWindow WPObject_wpQueryMinWindow
#define cmdhroot_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define cmdhroot_wpQueryStyle WPObject_wpQueryStyle
#define cmdhroot_wpSetTaskRec WPObject_wpSetTaskRec
#define cmdhroot_wpFindTaskRec WPObject_wpFindTaskRec
#define cmdhroot_wpQueryTitle WPObject_wpQueryTitle
#define cmdhroot_wpRegisterView WPObject_wpRegisterView
#define cmdhroot_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define cmdhroot_wpRender WPObject_wpRender
#define cmdhroot_wpRenderComplete WPObject_wpRenderComplete
#define cmdhroot_wpReplaceObject WPObject_wpReplaceObject
#define cmdhroot_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define cmdhroot_wpRestore WPObject_wpRestore
#define cmdhroot_wpRestoreData WPObject_wpRestoreData
#define cmdhroot_wpRestoreLong WPObject_wpRestoreLong
#define cmdhroot_wpRestoreState WPObject_wpRestoreState
#define cmdhroot_wpRestoreString WPObject_wpRestoreString
#define cmdhroot_wpSaveData WPObject_wpSaveData
#define cmdhroot_wpSaveImmediate WPObject_wpSaveImmediate
#define cmdhroot_wpSaveDeferred WPObject_wpSaveDeferred
#define cmdhroot_wpSaveLong WPObject_wpSaveLong
#define cmdhroot_wpSaveState WPObject_wpSaveState
#define cmdhroot_wpSaveString WPObject_wpSaveString
#define cmdhroot_wpScanSetupString WPObject_wpScanSetupString
#define cmdhroot_wpSetConcurrentView WPObject_wpSetConcurrentView
#define cmdhroot_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define cmdhroot_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define cmdhroot_wpSetDefaultView WPObject_wpSetDefaultView
#define cmdhroot_wpSetError WPObject_wpSetError
#define cmdhroot_wpSetIconHandle WPObject_wpSetIconHandle
#define cmdhroot_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define cmdhroot_wpSetupOnce WPObject_wpSetupOnce
#define cmdhroot_wpSetIcon WPObject_wpSetIcon
#define cmdhroot_wpSetIconData WPObject_wpSetIconData
#define cmdhroot_wpSetMinWindow WPObject_wpSetMinWindow
#define cmdhroot_wpSetStyle WPObject_wpSetStyle
#define cmdhroot_wpModifyStyle WPObject_wpModifyStyle
#define cmdhroot_wpSetTitle WPObject_wpSetTitle
#define cmdhroot_wpSetup WPObject_wpSetup
#define cmdhroot_wpSwitchTo WPObject_wpSwitchTo
#define cmdhroot_wpUnInitData WPObject_wpUnInitData
#define cmdhroot_wpViewObject WPObject_wpViewObject
#define cmdhroot_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define cmdhroot_wpQueryHandle WPObject_wpQueryHandle
#define cmdhroot_wpUnlockObject WPObject_wpUnlockObject
#define cmdhroot_wpObjectReady WPObject_wpObjectReady
#define cmdhroot_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define cmdhroot_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define cmdhroot_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define cmdhroot_wpIsDeleteable WPObject_wpIsDeleteable
#define cmdhroot_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define cmdhroot_wpSetObjectID WPObject_wpSetObjectID
#define cmdhroot_wpQueryObjectID WPObject_wpQueryObjectID
#define cmdhroot_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define cmdhroot_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define cmdhroot_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define cmdhroot_wpFindViewItem WPObject_wpFindViewItem
#define cmdhroot_wpLockObject WPObject_wpLockObject
#define cmdhroot_wpIsLocked WPObject_wpIsLocked
#define cmdhroot_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define cmdhroot_wpWaitForClose WPObject_wpWaitForClose
#define cmdhroot_somDefaultInit SOMObject_somDefaultInit
#define cmdhroot_somDestruct SOMObject_somDestruct
#define cmdhroot_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define cmdhroot_somDefaultAssign SOMObject_somDefaultAssign
#define cmdhroot_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define cmdhroot_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define cmdhroot_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define cmdhroot_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define cmdhroot_somDefaultVAssign SOMObject_somDefaultVAssign
#define cmdhroot_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define cmdhroot_somInit SOMObject_somInit
#define cmdhroot_somFree SOMObject_somFree
#define cmdhroot_somUninit SOMObject_somUninit
#define cmdhroot_somGetClass SOMObject_somGetClass
#define cmdhroot_somGetClassName SOMObject_somGetClassName
#define cmdhroot_somGetSize SOMObject_somGetSize
#define cmdhroot_somIsA SOMObject_somIsA
#define cmdhroot_somIsInstanceOf SOMObject_somIsInstanceOf
#define cmdhroot_somRespondsTo SOMObject_somRespondsTo
#define cmdhroot_somDispatch SOMObject_somDispatch
#define cmdhroot_somClassDispatch SOMObject_somClassDispatch
#define cmdhroot_somCastObj SOMObject_somCastObj
#define cmdhroot_somResetObj SOMObject_somResetObj
#define cmdhroot_somDispatchV SOMObject_somDispatchV
#define cmdhroot_somDispatchL SOMObject_somDispatchL
#define cmdhroot_somDispatchA SOMObject_somDispatchA
#define cmdhroot_somDispatchD SOMObject_somDispatchD
#define cmdhroot_somPrintSelf SOMObject_somPrintSelf
#define cmdhroot_somDumpSelf SOMObject_somDumpSelf
#define cmdhroot_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_cmdhroot_h */

#ifndef SOM_M_cmdhroot_h
#define SOM_M_cmdhroot_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_cmdhroot
#define M_cmdhroot SOMObject
#endif
#include <wpdisk.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_cmdhroot_HMODULE;
typedef
unsigned long  M_cmdhroot_HPOINTER;
typedef
string  M_cmdhroot_PSZ;

/*
 *  New class methods
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_cmdhroot_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_cmdhroot_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_cmdhroot_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_cmdhroot_MajorVersion 1
#define M_cmdhroot_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_cmdhrootNewClass cmdhrootc
#pragma linkage(cmdhrootc, system)
#define M_cmdhrootClassData cmdhrootd
#define M_cmdhrootCClassData cmdhrootx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_cmdhroot_classObj M_cmdhrootClassData.classObject
#define _M_cmdhroot M_cmdhroot_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_cmdhrootNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_cmdhrootNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_cmdhrootClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
} SOMDLINK M_cmdhrootClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_cmdhrootCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_cmdhrootCClassData;

/*
 * New and Renew macros for M_cmdhroot
 */
#define M_cmdhrootNew() \
   (_somNew(_M_cmdhroot ? _M_cmdhroot : M_cmdhrootNewClass(M_cmdhroot_MajorVersion, M_cmdhroot_MinorVersion)))
#define M_cmdhrootRenew(buf) \
   (_somRenew(_M_cmdhroot ? _M_cmdhroot : M_cmdhrootNewClass(M_cmdhroot_MajorVersion, M_cmdhroot_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_cmdhroot_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_cmdhroot_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsCreateDefaultTemplates
 */
#define M_cmdhroot_wpclsCreateDefaultTemplates(somSelf,Folder) \
	M_WPObject_wpclsCreateDefaultTemplates(somSelf,Folder)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_cmdhroot_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_cmdhroot_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_cmdhroot_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_cmdhroot_wpclsNew M_WPObject_wpclsNew
#define M_cmdhroot_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_cmdhroot_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_cmdhroot_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_cmdhroot_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_cmdhroot_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_cmdhroot_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_cmdhroot_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_cmdhroot_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_cmdhroot_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_cmdhroot_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_cmdhroot_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_cmdhroot_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_cmdhroot_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_cmdhroot_wpclsSetError M_WPObject_wpclsSetError
#define M_cmdhroot_wpclsQueryError M_WPObject_wpclsQueryError
#define M_cmdhroot_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_cmdhroot_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_cmdhroot_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_cmdhroot_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_cmdhroot_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_cmdhroot_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_cmdhroot_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_cmdhroot_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_cmdhroot_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_cmdhroot_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_cmdhroot_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_cmdhroot_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_cmdhroot_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_cmdhroot__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_cmdhroot__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_cmdhroot__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_cmdhroot__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_cmdhroot_somNew SOMClass_somNew
#define M_cmdhroot_somNewNoInit SOMClass_somNewNoInit
#define M_cmdhroot_somRenew SOMClass_somRenew
#define M_cmdhroot_somRenewNoInit SOMClass_somRenewNoInit
#define M_cmdhroot_somRenewNoZero SOMClass_somRenewNoZero
#define M_cmdhroot_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_cmdhroot_somAllocate SOMClass_somAllocate
#define M_cmdhroot_somDeallocate SOMClass_somDeallocate
#define M_cmdhroot__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_cmdhroot__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_cmdhroot_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_cmdhroot_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_cmdhroot_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_cmdhroot_somInitClass SOMClass_somInitClass
#define M_cmdhroot_somInitMIClass SOMClass_somInitMIClass
#define M_cmdhroot_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_cmdhroot_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_cmdhroot_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_cmdhroot_somClassReady SOMClass_somClassReady
#define M_cmdhroot_somGetApplyStub SOMClass_somGetApplyStub
#define M_cmdhroot_somGetClassData SOMClass_somGetClassData
#define M_cmdhroot_somSetClassData SOMClass_somSetClassData
#define M_cmdhroot_somGetClassMtab SOMClass_somGetClassMtab
#define M_cmdhroot_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_cmdhroot_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_cmdhroot_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_cmdhroot_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_cmdhroot_somGetMemberToken SOMClass_somGetMemberToken
#define M_cmdhroot_somGetMethodData SOMClass_somGetMethodData
#define M_cmdhroot_somGetRdStub SOMClass_somGetRdStub
#define M_cmdhroot_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_cmdhroot_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_cmdhroot_somGetMethodToken SOMClass_somGetMethodToken
#define M_cmdhroot_somGetName SOMClass_somGetName
#define M_cmdhroot_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_cmdhroot_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_cmdhroot_somGetNumMethods SOMClass_somGetNumMethods
#define M_cmdhroot_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_cmdhroot_somGetParent SOMClass_somGetParent
#define M_cmdhroot_somGetParents SOMClass_somGetParents
#define M_cmdhroot_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_cmdhroot_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_cmdhroot_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_cmdhroot_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_cmdhroot_somFindMethod SOMClass_somFindMethod
#define M_cmdhroot_somFindMethodOk SOMClass_somFindMethodOk
#define M_cmdhroot_somFindSMethod SOMClass_somFindSMethod
#define M_cmdhroot_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_cmdhroot_somLookupMethod SOMClass_somLookupMethod
#define M_cmdhroot_somCheckVersion SOMClass_somCheckVersion
#define M_cmdhroot_somDescendedFrom SOMClass_somDescendedFrom
#define M_cmdhroot_somSupportsMethod SOMClass_somSupportsMethod
#define M_cmdhroot_somDefinedMethod SOMClass_somDefinedMethod
#define M_cmdhroot_somOverrideMtab SOMClass_somOverrideMtab
#define M_cmdhroot_somDefaultInit SOMObject_somDefaultInit
#define M_cmdhroot_somDestruct SOMObject_somDestruct
#define M_cmdhroot_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_cmdhroot_somDefaultAssign SOMObject_somDefaultAssign
#define M_cmdhroot_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_cmdhroot_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_cmdhroot_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_cmdhroot_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_cmdhroot_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_cmdhroot_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_cmdhroot_somInit SOMObject_somInit
#define M_cmdhroot_somFree SOMObject_somFree
#define M_cmdhroot_somUninit SOMObject_somUninit
#define M_cmdhroot_somGetClass SOMObject_somGetClass
#define M_cmdhroot_somGetClassName SOMObject_somGetClassName
#define M_cmdhroot_somGetSize SOMObject_somGetSize
#define M_cmdhroot_somIsA SOMObject_somIsA
#define M_cmdhroot_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_cmdhroot_somRespondsTo SOMObject_somRespondsTo
#define M_cmdhroot_somDispatch SOMObject_somDispatch
#define M_cmdhroot_somClassDispatch SOMObject_somClassDispatch
#define M_cmdhroot_somCastObj SOMObject_somCastObj
#define M_cmdhroot_somResetObj SOMObject_somResetObj
#define M_cmdhroot_somDispatchV SOMObject_somDispatchV
#define M_cmdhroot_somDispatchL SOMObject_somDispatchL
#define M_cmdhroot_somDispatchA SOMObject_somDispatchA
#define M_cmdhroot_somDispatchD SOMObject_somDispatchD
#define M_cmdhroot_somPrintSelf SOMObject_somPrintSelf
#define M_cmdhroot_somDumpSelf SOMObject_somDumpSelf
#define M_cmdhroot_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_cmdhroot_h */

#ifndef SOM_cmdherefolder_h
#define SOM_cmdherefolder_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef cmdherefolder
#define cmdherefolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define cmdherefolder_MajorVersion 1
#define cmdherefolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define cmdherefolderNewClass cmdherec
#pragma linkage(cmdherec, system)
#define cmdherefolderClassData cmdhered
#define cmdherefolderCClassData cmdherex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cmdhere.h>
/*--------------Migration------------*/
#define cmdherefolder_classObj cmdherefolderClassData.classObject
#define _cmdherefolder cmdherefolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK cmdherefolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(cmdherefolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct cmdherefolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK cmdherefolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct cmdherefolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK cmdherefolderCClassData;

/*
 * New and Renew macros for cmdherefolder
 */
#define cmdherefolderNew() \
   (_somNew(_cmdherefolder ? _cmdherefolder : cmdherefolderNewClass(cmdherefolder_MajorVersion, cmdherefolder_MinorVersion)))
#define cmdherefolderRenew(buf) \
   (_somRenew(_cmdherefolder ? _cmdherefolder : cmdherefolderNewClass(cmdherefolder_MajorVersion, cmdherefolder_MinorVersion), buf))

/*
 * Override method: wpModifyPopupMenu
 */
#define cmdherefolder_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define cmdherefolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define cmdherefolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define cmdherefolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define cmdherefolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define cmdherefolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define cmdherefolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define cmdherefolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define cmdherefolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define cmdherefolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define cmdherefolder_wpPopulate WPFolder_wpPopulate
#define cmdherefolder_wpQueryContent WPFolder_wpQueryContent
#define cmdherefolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define cmdherefolder_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define cmdherefolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define cmdherefolder_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define cmdherefolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define cmdherefolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define cmdherefolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define cmdherefolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define cmdherefolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define cmdherefolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define cmdherefolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define cmdherefolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define cmdherefolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define cmdherefolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define cmdherefolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define cmdherefolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define cmdherefolder_wpDeleteContents WPFolder_wpDeleteContents
#define cmdherefolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define cmdherefolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define cmdherefolder_wpSearchFolder WPFolder_wpSearchFolder
#define cmdherefolder_wpContainsFolders WPFolder_wpContainsFolders
#define cmdherefolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define cmdherefolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define cmdherefolder_wpAddToContent WPFolder_wpAddToContent
#define cmdherefolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define cmdherefolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define cmdherefolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define cmdherefolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define cmdherefolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define cmdherefolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define cmdherefolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define cmdherefolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define cmdherefolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define cmdherefolder_wpSetRealName WPFileSystem_wpSetRealName
#define cmdherefolder_wpSetType WPFileSystem_wpSetType
#define cmdherefolder_wpQueryType WPFileSystem_wpQueryType
#define cmdherefolder_wpSetAttr WPFileSystem_wpSetAttr
#define cmdherefolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define cmdherefolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define cmdherefolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define cmdherefolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define cmdherefolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define cmdherefolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define cmdherefolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define cmdherefolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define cmdherefolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define cmdherefolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define cmdherefolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define cmdherefolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define cmdherefolder_wpRefresh WPFileSystem_wpRefresh
#define cmdherefolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define cmdherefolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define cmdherefolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define cmdherefolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define cmdherefolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define cmdherefolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define cmdherefolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define cmdherefolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define cmdherefolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define cmdherefolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define cmdherefolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define cmdherefolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define cmdherefolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define cmdherefolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define cmdherefolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define cmdherefolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define cmdherefolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define cmdherefolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define cmdherefolder_wpAllocMem WPObject_wpAllocMem
#define cmdherefolder_wpAppendObject WPObject_wpAppendObject
#define cmdherefolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define cmdherefolder_wpClose WPObject_wpClose
#define cmdherefolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define cmdherefolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define cmdherefolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define cmdherefolder_wpConfirmDelete WPObject_wpConfirmDelete
#define cmdherefolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define cmdherefolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define cmdherefolder_wpCopyObject WPObject_wpCopyObject
#define cmdherefolder_wpCreateAnother WPObject_wpCreateAnother
#define cmdherefolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define cmdherefolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define cmdherefolder_wpDelete WPObject_wpDelete
#define cmdherefolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define cmdherefolder_wpDisplayHelp WPObject_wpDisplayHelp
#define cmdherefolder_wpDisplayMenu WPObject_wpDisplayMenu
#define cmdherefolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define cmdherefolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define cmdherefolder_wpDragOver WPObject_wpDragOver
#define cmdherefolder_wpDrop WPObject_wpDrop
#define cmdherefolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define cmdherefolder_wpEndConversation WPObject_wpEndConversation
#define cmdherefolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define cmdherefolder_wpFindUseItem WPObject_wpFindUseItem
#define cmdherefolder_wpFormatDragItem WPObject_wpFormatDragItem
#define cmdherefolder_wpFree WPObject_wpFree
#define cmdherefolder_wpFreeMem WPObject_wpFreeMem
#define cmdherefolder_wpHide WPObject_wpHide
#define cmdherefolder_wpInitData WPObject_wpInitData
#define cmdherefolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define cmdherefolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define cmdherefolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define cmdherefolder_wpMoveObject WPObject_wpMoveObject
#define cmdherefolder_wpOpen WPObject_wpOpen
#define cmdherefolder_wpPrintObject WPObject_wpPrintObject
#define cmdherefolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define cmdherefolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define cmdherefolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define cmdherefolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define cmdherefolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define cmdherefolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define cmdherefolder_wpQueryError WPObject_wpQueryError
#define cmdherefolder_wpSetFolder WPObject_wpSetFolder
#define cmdherefolder_wpQueryFolder WPObject_wpQueryFolder
#define cmdherefolder_wpQueryIcon WPObject_wpQueryIcon
#define cmdherefolder_wpQueryIconData WPObject_wpQueryIconData
#define cmdherefolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define cmdherefolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define cmdherefolder_wpQueryStyle WPObject_wpQueryStyle
#define cmdherefolder_wpSetTaskRec WPObject_wpSetTaskRec
#define cmdherefolder_wpFindTaskRec WPObject_wpFindTaskRec
#define cmdherefolder_wpQueryTitle WPObject_wpQueryTitle
#define cmdherefolder_wpRegisterView WPObject_wpRegisterView
#define cmdherefolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define cmdherefolder_wpRender WPObject_wpRender
#define cmdherefolder_wpRenderComplete WPObject_wpRenderComplete
#define cmdherefolder_wpReplaceObject WPObject_wpReplaceObject
#define cmdherefolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define cmdherefolder_wpRestore WPObject_wpRestore
#define cmdherefolder_wpRestoreData WPObject_wpRestoreData
#define cmdherefolder_wpRestoreLong WPObject_wpRestoreLong
#define cmdherefolder_wpRestoreState WPObject_wpRestoreState
#define cmdherefolder_wpRestoreString WPObject_wpRestoreString
#define cmdherefolder_wpSaveData WPObject_wpSaveData
#define cmdherefolder_wpSaveImmediate WPObject_wpSaveImmediate
#define cmdherefolder_wpSaveDeferred WPObject_wpSaveDeferred
#define cmdherefolder_wpSaveLong WPObject_wpSaveLong
#define cmdherefolder_wpSaveState WPObject_wpSaveState
#define cmdherefolder_wpSaveString WPObject_wpSaveString
#define cmdherefolder_wpScanSetupString WPObject_wpScanSetupString
#define cmdherefolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define cmdherefolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define cmdherefolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define cmdherefolder_wpSetDefaultView WPObject_wpSetDefaultView
#define cmdherefolder_wpSetError WPObject_wpSetError
#define cmdherefolder_wpSetIconHandle WPObject_wpSetIconHandle
#define cmdherefolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define cmdherefolder_wpSetupOnce WPObject_wpSetupOnce
#define cmdherefolder_wpSetIcon WPObject_wpSetIcon
#define cmdherefolder_wpSetIconData WPObject_wpSetIconData
#define cmdherefolder_wpSetMinWindow WPObject_wpSetMinWindow
#define cmdherefolder_wpSetStyle WPObject_wpSetStyle
#define cmdherefolder_wpModifyStyle WPObject_wpModifyStyle
#define cmdherefolder_wpSetTitle WPObject_wpSetTitle
#define cmdherefolder_wpSetup WPObject_wpSetup
#define cmdherefolder_wpSwitchTo WPObject_wpSwitchTo
#define cmdherefolder_wpUnInitData WPObject_wpUnInitData
#define cmdherefolder_wpViewObject WPObject_wpViewObject
#define cmdherefolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define cmdherefolder_wpQueryHandle WPObject_wpQueryHandle
#define cmdherefolder_wpUnlockObject WPObject_wpUnlockObject
#define cmdherefolder_wpObjectReady WPObject_wpObjectReady
#define cmdherefolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define cmdherefolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define cmdherefolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define cmdherefolder_wpIsDeleteable WPObject_wpIsDeleteable
#define cmdherefolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define cmdherefolder_wpSetObjectID WPObject_wpSetObjectID
#define cmdherefolder_wpQueryObjectID WPObject_wpQueryObjectID
#define cmdherefolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define cmdherefolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define cmdherefolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define cmdherefolder_wpFindViewItem WPObject_wpFindViewItem
#define cmdherefolder_wpLockObject WPObject_wpLockObject
#define cmdherefolder_wpIsLocked WPObject_wpIsLocked
#define cmdherefolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define cmdherefolder_wpWaitForClose WPObject_wpWaitForClose
#define cmdherefolder_somDefaultInit SOMObject_somDefaultInit
#define cmdherefolder_somDestruct SOMObject_somDestruct
#define cmdherefolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define cmdherefolder_somDefaultAssign SOMObject_somDefaultAssign
#define cmdherefolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define cmdherefolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define cmdherefolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define cmdherefolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define cmdherefolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define cmdherefolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define cmdherefolder_somInit SOMObject_somInit
#define cmdherefolder_somFree SOMObject_somFree
#define cmdherefolder_somUninit SOMObject_somUninit
#define cmdherefolder_somGetClass SOMObject_somGetClass
#define cmdherefolder_somGetClassName SOMObject_somGetClassName
#define cmdherefolder_somGetSize SOMObject_somGetSize
#define cmdherefolder_somIsA SOMObject_somIsA
#define cmdherefolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define cmdherefolder_somRespondsTo SOMObject_somRespondsTo
#define cmdherefolder_somDispatch SOMObject_somDispatch
#define cmdherefolder_somClassDispatch SOMObject_somClassDispatch
#define cmdherefolder_somCastObj SOMObject_somCastObj
#define cmdherefolder_somResetObj SOMObject_somResetObj
#define cmdherefolder_somDispatchV SOMObject_somDispatchV
#define cmdherefolder_somDispatchL SOMObject_somDispatchL
#define cmdherefolder_somDispatchA SOMObject_somDispatchA
#define cmdherefolder_somDispatchD SOMObject_somDispatchD
#define cmdherefolder_somPrintSelf SOMObject_somPrintSelf
#define cmdherefolder_somDumpSelf SOMObject_somDumpSelf
#define cmdherefolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_cmdherefolder_h */

#ifndef SOM_M_cmdherefolder_h
#define SOM_M_cmdherefolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_cmdherefolder
#define M_cmdherefolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
typedef
unsigned long  M_cmdherefolder_HMODULE;
typedef
unsigned long  M_cmdherefolder_HPOINTER;
typedef
string  M_cmdherefolder_PSZ;

/*
 *  New class methods
 *  HMODULE clsGetResourceModule();
 */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HMODULE
    #ifdef HMODULE
        #undef HMODULE
        #define SOMTGD_HMODULE 1
    #else
        #define HMODULE M_cmdherefolder_HMODULE
    #endif /* HMODULE */
#endif /* SOMTGD_HMODULE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_HPOINTER
    #ifdef HPOINTER
        #undef HPOINTER
        #define SOMTGD_HPOINTER 1
    #else
        #define HPOINTER M_cmdherefolder_HPOINTER
    #endif /* HPOINTER */
#endif /* SOMTGD_HPOINTER */
#endif /* SOM_DONT_USE_SHORT_NAMES */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSZ
    #ifdef PSZ
        #undef PSZ
        #define SOMTGD_PSZ 1
    #else
        #define PSZ M_cmdherefolder_PSZ
    #endif /* PSZ */
#endif /* SOMTGD_PSZ */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of user-defined types.
 */

#define M_cmdherefolder_MajorVersion 1
#define M_cmdherefolder_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_cmdherefolderNewClass cmdherec
#pragma linkage(cmdherec, system)
#define M_cmdherefolderClassData cmdhered
#define M_cmdherefolderCClassData cmdherex
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_cmdherefolder_classObj M_cmdherefolderClassData.classObject
#define _M_cmdherefolder M_cmdherefolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_cmdherefolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_cmdherefolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_cmdherefolderClassDataStructure {
	SOMClass *classObject;
	somMToken _get_hmodResource;
	somMToken _set_hmodResource;
	somMToken _get_hMyIcon;
	somMToken _set_hMyIcon;
} SOMDLINK M_cmdherefolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_cmdherefolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_cmdherefolderCClassData;

/*
 * New and Renew macros for M_cmdherefolder
 */
#define M_cmdherefolderNew() \
   (_somNew(_M_cmdherefolder ? _M_cmdherefolder : M_cmdherefolderNewClass(M_cmdherefolder_MajorVersion, M_cmdherefolder_MinorVersion)))
#define M_cmdherefolderRenew(buf) \
   (_somRenew(_M_cmdherefolder ? _M_cmdherefolder : M_cmdherefolderNewClass(M_cmdherefolder_MajorVersion, M_cmdherefolder_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_cmdherefolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_cmdherefolder_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsCreateDefaultTemplates
 */
#define M_cmdherefolder_wpclsCreateDefaultTemplates(somSelf,Folder) \
	M_WPObject_wpclsCreateDefaultTemplates(somSelf,Folder)

/*
 * New Method: _get_hmodResource
 */
typedef M_cmdherefolder_HMODULE   SOMLINK somTP_M_cmdherefolder__get_hmodResource(M_cmdherefolder *somSelf);
#pragma linkage(somTP_M_cmdherefolder__get_hmodResource, system)
typedef somTP_M_cmdherefolder__get_hmodResource *somTD_M_cmdherefolder__get_hmodResource;
#define somMD_M_cmdherefolder__get_hmodResource "::M_cmdherefolder::_get_hmodResource"
#define M_cmdherefolder__get_hmodResource(somSelf) \
    (SOM_Resolve(somSelf, M_cmdherefolder, _get_hmodResource) \
	(somSelf))
#ifndef SOMGD_get_hmodResource
    #if (defined(_get_hmodResource) || defined(__get_hmodResource))
        #undef _get_hmodResource
        #undef __get_hmodResource
        #define SOMGD_get_hmodResource 1
    #else
        #define __get_hmodResource M_cmdherefolder__get_hmodResource
    #endif /* __get_hmodResource */
#endif /* SOMGD_get_hmodResource */

/*
 * New Method: _set_hmodResource
 */
typedef void   SOMLINK somTP_M_cmdherefolder__set_hmodResource(M_cmdherefolder *somSelf,
		M_cmdherefolder_HMODULE hmodResource);
#pragma linkage(somTP_M_cmdherefolder__set_hmodResource, system)
typedef somTP_M_cmdherefolder__set_hmodResource *somTD_M_cmdherefolder__set_hmodResource;
#define somMD_M_cmdherefolder__set_hmodResource "::M_cmdherefolder::_set_hmodResource"
#define M_cmdherefolder__set_hmodResource(somSelf,hmodResource) \
    (SOM_Resolve(somSelf, M_cmdherefolder, _set_hmodResource) \
	(somSelf,hmodResource))
#ifndef SOMGD_set_hmodResource
    #if (defined(_set_hmodResource) || defined(__set_hmodResource))
        #undef _set_hmodResource
        #undef __set_hmodResource
        #define SOMGD_set_hmodResource 1
    #else
        #define __set_hmodResource M_cmdherefolder__set_hmodResource
    #endif /* __set_hmodResource */
#endif /* SOMGD_set_hmodResource */

/*
 * New Method: _get_hMyIcon
 */
typedef M_cmdherefolder_HPOINTER   SOMLINK somTP_M_cmdherefolder__get_hMyIcon(M_cmdherefolder *somSelf);
#pragma linkage(somTP_M_cmdherefolder__get_hMyIcon, system)
typedef somTP_M_cmdherefolder__get_hMyIcon *somTD_M_cmdherefolder__get_hMyIcon;
#define somMD_M_cmdherefolder__get_hMyIcon "::M_cmdherefolder::_get_hMyIcon"
#define M_cmdherefolder__get_hMyIcon(somSelf) \
    (SOM_Resolve(somSelf, M_cmdherefolder, _get_hMyIcon) \
	(somSelf))
#ifndef SOMGD_get_hMyIcon
    #if (defined(_get_hMyIcon) || defined(__get_hMyIcon))
        #undef _get_hMyIcon
        #undef __get_hMyIcon
        #define SOMGD_get_hMyIcon 1
    #else
        #define __get_hMyIcon M_cmdherefolder__get_hMyIcon
    #endif /* __get_hMyIcon */
#endif /* SOMGD_get_hMyIcon */

/*
 * New Method: _set_hMyIcon
 */
typedef void   SOMLINK somTP_M_cmdherefolder__set_hMyIcon(M_cmdherefolder *somSelf,
		M_cmdherefolder_HPOINTER hMyIcon);
#pragma linkage(somTP_M_cmdherefolder__set_hMyIcon, system)
typedef somTP_M_cmdherefolder__set_hMyIcon *somTD_M_cmdherefolder__set_hMyIcon;
#define somMD_M_cmdherefolder__set_hMyIcon "::M_cmdherefolder::_set_hMyIcon"
#define M_cmdherefolder__set_hMyIcon(somSelf,hMyIcon) \
    (SOM_Resolve(somSelf, M_cmdherefolder, _set_hMyIcon) \
	(somSelf,hMyIcon))
#ifndef SOMGD_set_hMyIcon
    #if (defined(_set_hMyIcon) || defined(__set_hMyIcon))
        #undef _set_hMyIcon
        #undef __set_hMyIcon
        #define SOMGD_set_hMyIcon 1
    #else
        #define __set_hMyIcon M_cmdherefolder__set_hMyIcon
    #endif /* __set_hMyIcon */
#endif /* SOMGD_set_hMyIcon */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_cmdherefolder_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_cmdherefolder_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_cmdherefolder_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_cmdherefolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_cmdherefolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_cmdherefolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_cmdherefolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_cmdherefolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_cmdherefolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_cmdherefolder_wpclsNew M_WPObject_wpclsNew
#define M_cmdherefolder_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_cmdherefolder_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_cmdherefolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_cmdherefolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_cmdherefolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_cmdherefolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_cmdherefolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_cmdherefolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_cmdherefolder_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_cmdherefolder_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_cmdherefolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_cmdherefolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_cmdherefolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_cmdherefolder_wpclsSetError M_WPObject_wpclsSetError
#define M_cmdherefolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_cmdherefolder_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_cmdherefolder_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_cmdherefolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_cmdherefolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_cmdherefolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_cmdherefolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_cmdherefolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_cmdherefolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_cmdherefolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_cmdherefolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_cmdherefolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_cmdherefolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_cmdherefolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_cmdherefolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_cmdherefolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_cmdherefolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_cmdherefolder__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_cmdherefolder_somNew SOMClass_somNew
#define M_cmdherefolder_somNewNoInit SOMClass_somNewNoInit
#define M_cmdherefolder_somRenew SOMClass_somRenew
#define M_cmdherefolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_cmdherefolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_cmdherefolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_cmdherefolder_somAllocate SOMClass_somAllocate
#define M_cmdherefolder_somDeallocate SOMClass_somDeallocate
#define M_cmdherefolder__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_cmdherefolder__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_cmdherefolder_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_cmdherefolder_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_cmdherefolder_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_cmdherefolder_somInitClass SOMClass_somInitClass
#define M_cmdherefolder_somInitMIClass SOMClass_somInitMIClass
#define M_cmdherefolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_cmdherefolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_cmdherefolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_cmdherefolder_somClassReady SOMClass_somClassReady
#define M_cmdherefolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_cmdherefolder_somGetClassData SOMClass_somGetClassData
#define M_cmdherefolder_somSetClassData SOMClass_somSetClassData
#define M_cmdherefolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_cmdherefolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_cmdherefolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_cmdherefolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_cmdherefolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_cmdherefolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_cmdherefolder_somGetMethodData SOMClass_somGetMethodData
#define M_cmdherefolder_somGetRdStub SOMClass_somGetRdStub
#define M_cmdherefolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_cmdherefolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_cmdherefolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_cmdherefolder_somGetName SOMClass_somGetName
#define M_cmdherefolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_cmdherefolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_cmdherefolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_cmdherefolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_cmdherefolder_somGetParent SOMClass_somGetParent
#define M_cmdherefolder_somGetParents SOMClass_somGetParents
#define M_cmdherefolder_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_cmdherefolder_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_cmdherefolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_cmdherefolder_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_cmdherefolder_somFindMethod SOMClass_somFindMethod
#define M_cmdherefolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_cmdherefolder_somFindSMethod SOMClass_somFindSMethod
#define M_cmdherefolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_cmdherefolder_somLookupMethod SOMClass_somLookupMethod
#define M_cmdherefolder_somCheckVersion SOMClass_somCheckVersion
#define M_cmdherefolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_cmdherefolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_cmdherefolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_cmdherefolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_cmdherefolder_somDefaultInit SOMObject_somDefaultInit
#define M_cmdherefolder_somDestruct SOMObject_somDestruct
#define M_cmdherefolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_cmdherefolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_cmdherefolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_cmdherefolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_cmdherefolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_cmdherefolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_cmdherefolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_cmdherefolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_cmdherefolder_somInit SOMObject_somInit
#define M_cmdherefolder_somFree SOMObject_somFree
#define M_cmdherefolder_somUninit SOMObject_somUninit
#define M_cmdherefolder_somGetClass SOMObject_somGetClass
#define M_cmdherefolder_somGetClassName SOMObject_somGetClassName
#define M_cmdherefolder_somGetSize SOMObject_somGetSize
#define M_cmdherefolder_somIsA SOMObject_somIsA
#define M_cmdherefolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_cmdherefolder_somRespondsTo SOMObject_somRespondsTo
#define M_cmdherefolder_somDispatch SOMObject_somDispatch
#define M_cmdherefolder_somClassDispatch SOMObject_somClassDispatch
#define M_cmdherefolder_somCastObj SOMObject_somCastObj
#define M_cmdherefolder_somResetObj SOMObject_somResetObj
#define M_cmdherefolder_somDispatchV SOMObject_somDispatchV
#define M_cmdherefolder_somDispatchL SOMObject_somDispatchL
#define M_cmdherefolder_somDispatchA SOMObject_somDispatchA
#define M_cmdherefolder_somDispatchD SOMObject_somDispatchD
#define M_cmdherefolder_somPrintSelf SOMObject_somPrintSelf
#define M_cmdherefolder_somDumpSelf SOMObject_somDumpSelf
#define M_cmdherefolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_cmdherefolder_h */
